package project

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// InstructionsDirName holds the materialised project bundle inside StateDirName.
const InstructionsDirName = "instructions"

// generatedHeader marks every file weft writes into a repository, so anyone who
// opens one knows it is regenerated and where to edit instead.
const generatedHeader = "<!-- generated by weft; edit the source, not this file -->"

// Part is one piece of a repository's project bundle, written as its own file so
// a harness that resolves imports can pull in exactly the parts it needs.
type Part struct {
	// Name identifies the part, e.g. a source name or a repo-relative input path.
	Name string
	// Origin says where it came from, and decides whether a given harness should
	// import it. A harness never imports the file it already reads itself.
	Origin Origin
	// Content is the assembled text.
	Content string
}

// Origin distinguishes the two things that feed a project bundle.
type Origin int

const (
	// OriginRules: selected by the resolver from weft's own sources.
	OriginRules Origin = iota
	// OriginInput: read from a project instruction file already in the
	// repository, e.g. a tracked CLAUDE.md.
	OriginInput
)

// WrittenPart pairs a part with the absolute path it landed at.
type WrittenPart struct {
	Part
	Path string
}

// StateDir returns the repository's weft directory.
func StateDir(root string) string { return filepath.Join(root, StateDirName) }

// InstructionsDir returns where the project bundle is materialised.
func InstructionsDir(root string) string {
	return filepath.Join(StateDir(root), InstructionsDirName)
}

// WriteParts materialises the project bundle under <root>/.weft/instructions,
// returning what it wrote in order.
//
// The directory is rebuilt each time rather than merged. These files are
// derived, they are excluded from git, and a stale part left behind would be
// imported forever by a harness that never asked for it. Rebuilding is the same
// choice the global staged tree makes for the same reason.
//
// Numbering preserves order in the filename, so an import list reads in priority
// order and a human listing the directory sees the same sequence the model does.
func WriteParts(root string, parts []Part) ([]WrittenPart, error) {
	dir := InstructionsDir(root)
	if err := os.RemoveAll(dir); err != nil {
		return nil, fmt.Errorf("project: clearing %s: %w", dir, err)
	}
	if len(parts) == 0 {
		return nil, nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, fmt.Errorf("project: creating %s: %w", dir, err)
	}

	written := make([]WrittenPart, 0, len(parts))
	for i, p := range parts {
		name := fmt.Sprintf("%02d-%s.md", i*10, slug(p.Name))
		path := filepath.Join(dir, name)
		body := generatedHeader + "\n\n" + strings.TrimSpace(p.Content) + "\n"
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil { //nolint:gosec // path is inside the repository's own weft dir
			return nil, fmt.Errorf("project: writing %s: %w", path, err)
		}
		written = append(written, WrittenPart{Part: p, Path: path})
	}
	return written, nil
}

// ClearState removes the repository's weft directory entirely, used when a
// project is forgotten or delivery is turned off for it.
func ClearState(root string) error {
	if err := os.RemoveAll(StateDir(root)); err != nil {
		return fmt.Errorf("project: removing %s: %w", StateDir(root), err)
	}
	return nil
}

// slugUnsafe matches everything not allowed in a generated filename.
var slugUnsafe = regexp.MustCompile(`[^a-zA-Z0-9._-]+`)

// slug turns a part name into a filename fragment. Repo-relative input paths
// carry slashes and dots, so they are flattened rather than creating
// directories inside the bundle.
//
// A trailing .md is dropped first: part names are usually filenames already, and
// keeping it would produce "00-claude.md.md" once the writer appends its own
// extension.
func slug(name string) string {
	trimmed := strings.TrimSpace(name)
	trimmed = strings.TrimSuffix(trimmed, filepath.Ext(trimmed))
	s := slugUnsafe.ReplaceAllString(trimmed, "-")
	s = strings.Trim(s, "-.")
	if s == "" {
		return "part"
	}
	return strings.ToLower(s)
}

// ImportPathsFor returns the parts a harness should import, excluding any input
// part the harness already reads for itself.
//
// Without the exclusion, Claude Code would import a copy of the repository's own
// CLAUDE.md that it has already loaded, and the model would see every rule in it
// twice. Rules the resolver selected are always included: they come from weft's
// sources, so no harness has them already.
func ImportPathsFor(written []WrittenPart, ownInputs []string) []string {
	skip := make(map[string]bool, len(ownInputs))
	for _, in := range ownInputs {
		skip[normaliseRel(in)] = true
	}
	out := make([]string, 0, len(written))
	for _, w := range written {
		if w.Origin == OriginInput && skip[normaliseRel(w.Name)] {
			continue
		}
		out = append(out, w.Path)
	}
	return out
}

// PartsFor returns the parts a harness should receive inline, using the same
// exclusion rule as ImportPathsFor.
func PartsFor(written []WrittenPart, ownInputs []string) []Part {
	skip := make(map[string]bool, len(ownInputs))
	for _, in := range ownInputs {
		skip[normaliseRel(in)] = true
	}
	out := make([]Part, 0, len(written))
	for _, w := range written {
		if w.Origin == OriginInput && skip[normaliseRel(w.Name)] {
			continue
		}
		out = append(out, w.Part)
	}
	return out
}

// SortInputs orders inputs by path for a stable bundle.
func SortInputs(in []Input) {
	sort.Slice(in, func(i, j int) bool { return in[i].Rel < in[j].Rel })
}
